spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: taskmanager
    password: taskmanager
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
  docker:
    compose:
      stop:
        command: down
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  security:
    jwt:
      cookieName: jwt
      refreshCookieName: jwt-refresh
      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expirationMs: 3600000
      refreshExpirationMs: 86400000