spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  docker:
    compose:
      stop:
        command: down
application:
  security:
    jwt:
      secret-key:
        404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970